// <auto-generated />
using ItShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItShop.Migrations
{
    [DbContext(typeof(ITShopContext))]
    [Migration("20250820150857_20aug-ver01")]
    partial class _20augver01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ItShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "IT group3",
                            ExtraDescription = "",
                            Name = "IT group"
                        },
                        new
                        {
                            Id = 2,
                            Description = "گروه لوازم برقی",
                            ExtraDescription = "",
                            Name = "لوازم برقی"
                        },
                        new
                        {
                            Id = 3,
                            Description = "ذخیره فایل",
                            ExtraDescription = "",
                            Name = "فلش"
                        },
                        new
                        {
                            Id = 4,
                            Description = "لوازم کامپیوتر",
                            ExtraDescription = "",
                            Name = "کیبورد"
                        },
                        new
                        {
                            Id = 5,
                            Description = "لواز کامپیوتر",
                            ExtraDescription = "",
                            Name = "موس"
                        },
                        new
                        {
                            Id = 6,
                            Description = "اوازم کامپیوتر",
                            ExtraDescription = "",
                            Name = "کیس"
                        },
                        new
                        {
                            Id = 7,
                            Description = "انواع هارد ",
                            ExtraDescription = "",
                            Name = "هارد"
                        },
                        new
                        {
                            Id = 8,
                            Description = "انواع لپتاپ",
                            ExtraDescription = "",
                            Name = "لپتاپ"
                        });
                });

            modelBuilder.Entity("ItShop.Models.CtegoryToProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("CtegoryToProducts");
                });

            modelBuilder.Entity("ItShop.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("QuantityInStook")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("items");
                });

            modelBuilder.Entity("ItShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("products");
                });

            modelBuilder.Entity("ItShop.Models.CtegoryToProduct", b =>
                {
                    b.HasOne("ItShop.Models.Category", "Category")
                        .WithMany("CtegoryToProducts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItShop.Models.Product", "Product")
                        .WithMany("CtegoryToProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ItShop.Models.Product", b =>
                {
                    b.HasOne("ItShop.Models.Item", "Item")
                        .WithOne("product")
                        .HasForeignKey("ItShop.Models.Product", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ItShop.Models.Category", b =>
                {
                    b.Navigation("CtegoryToProducts");
                });

            modelBuilder.Entity("ItShop.Models.Item", b =>
                {
                    b.Navigation("product")
                        .IsRequired();
                });

            modelBuilder.Entity("ItShop.Models.Product", b =>
                {
                    b.Navigation("CtegoryToProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
